Repository boostcampwm-2021/web24-boostris, pull requests merged in 2021-11, with the labels that each got.

#101 🛠 : typescript를 사용하기 위한 express 세팅(api-server)
  back-end/api-server/package-lock.json
  back-end/api-server/package.json
  back-end/api-server/src/index.ts
  back-end/api-server/tsconfig.json
Labels: 공통

#108 테트리스 키보드 이벤트, 회전 기능 추가
  front-end/public/assets/block.png
  front-end/public/assets/board.png
  front-end/src/components/Tetris/Board/index.tsx
  front-end/src/components/Tetris/RealBoard/index.tsx
  front-end/src/constants/tetris.ts
Labels: 🧱 테트리스 기능, 🖥. 프론트엔드

#106 로그인 / 회원가입 페이지 관련 작업 모음
  back-end/api-server/package-lock.json
  back-end/api-server/package.json
  back-end/api-server/src/index.ts
  front-end/package-lock.json
  front-end/package.json
  front-end/public/index.html
  front-end/src/App.scss
  front-end/src/App.tsx
  front-end/src/components/BasicButton/index.tsx
  front-end/src/components/BasicButton/style.scss
  front-end/src/components/BasicInput/index.tsx
  front-end/src/components/BasicInput/style.scss
  front-end/src/components/Modal/index.tsx
  front-end/src/components/Modal/style.scss
  front-end/src/components/OauthLoginButton/index.tsx
  front-end/src/components/OauthLoginButton/style.scss
  front-end/src/components/login.tsx
  front-end/src/components/naver.tsx
  front-end/src/index.scss
  front-end/src/pages/LobbyPage/index.tsx
  front-end/src/pages/LoginPage/index.tsx
  front-end/src/pages/LoginPage/style.scss
  front-end/src/pages/RegisterPage/index.tsx
  front-end/src/pages/RegisterPage/style.scss
Labels: 🖥. 프론트엔드, 공통

#110 Oauth 로그인 관련 코드 전체 병합
  back-end/api-server/database/connect.ts
  back-end/api-server/database/query.ts
  back-end/api-server/package-lock.json
  back-end/api-server/package.json
  back-end/api-server/routes/auth.ts
  back-end/api-server/services/auth.ts
  back-end/api-server/src/index.ts
  back-end/api-server/tsconfig.json
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.tsx
  front-end/src/components/OauthLoginButton/index.tsx
  front-end/src/components/OauthLoginButton/style.scss
  front-end/src/components/login.tsx
  front-end/src/components/naver.tsx
  front-end/src/constants/index.js
  front-end/src/constants/index.ts
  front-end/src/hooks/use-query-params/index.ts
  front-end/src/pages/LobbyPage/index.tsx
  front-end/src/pages/LoginPage/index.tsx
  front-end/src/routes/OauthCallbackRouter/GithubCallback.tsx
  front-end/src/routes/OauthCallbackRouter/GoogleCallback.tsx
  front-end/src/routes/OauthCallbackRouter/NaverCallback.tsx
  front-end/src/routes/OauthCallbackRouter/index.tsx
  front-end/src/routes/PrivateRoute.tsx
Labels: 로그인🔑, 🖥. 프론트엔드, 🗄 백엔드, 공통

#111 [회원 가입] 기존 회원 여부 판단, 검증 후 DB Insert
  back-end/api-server/database/query.ts
  back-end/api-server/routes/auth.ts
  back-end/api-server/routes/registerDBInsert.ts
  back-end/api-server/routes/registerDupCheck.ts
  back-end/api-server/src/index.ts
  front-end/src/components/BasicButton/index.tsx
  front-end/src/components/BasicButton/style.scss
  front-end/src/components/BasicInput/index.tsx
  front-end/src/pages/RegisterPage/index.tsx
  front-end/src/routes/OauthCallbackRouter/GithubCallback.tsx
  front-end/src/routes/OauthCallbackRouter/GoogleCallback.tsx
  front-end/src/routes/OauthCallbackRouter/NaverCallback.tsx
Labels: 로그인🔑, 🖥. 프론트엔드, 🗄 백엔드

#114 로비 페이지 마크업 진행
  front-end/public/assets/logo_appbar.png
  front-end/src/App.tsx
  front-end/src/common/styles/_base.scss
  front-end/src/components/SectionTitle/index.tsx
  front-end/src/components/SectionTitle/style.scss
  front-end/src/layout/AppbarLayout/index.tsx
  front-end/src/layout/AppbarLayout/style.scss
  front-end/src/pages/LobbyPage/index.tsx
  front-end/src/pages/LobbyPage/style.scss
Labels: 🏠. 대기실, 🖥. 프론트엔드

#117 💄 : 로비 화면 스타일 버그 수정
  front-end/src/App.scss
  front-end/src/layout/AppbarLayout/index.tsx
  front-end/src/layout/AppbarLayout/style.scss
  front-end/src/pages/LobbyPage/style.scss
Labels: bug, 🖥. 프론트엔드

#119 🔨 : 기존 로직을 redux 기반으로 리팩토링 진행 (github Oauth)
  back-end/api-server/routes/auth.ts
  front-end/src/app/store.ts
  front-end/src/features/user/userAPI.ts
  front-end/src/features/user/userSlice.ts
  front-end/src/hooks/use-query-params/index.ts
  front-end/src/pages/RegisterPage/index.tsx
  front-end/src/routes/OauthCallbackRouter/GithubCallback.tsx
Labels: 로그인🔑, 🖥. 프론트엔드, 🗄 백엔드, 공통

#121 Oauth 로그인 redux 기반 리팩토링 진행
  back-end/api-server/routes/auth.ts
  front-end/src/components/BasicButton/index.tsx
  front-end/src/components/BasicInput/index.tsx
  front-end/src/components/OauthLoginButton/index.tsx
  front-end/src/constants/index.ts
  front-end/src/features/user/userAPI.ts
  front-end/src/features/user/userSlice.ts
  front-end/src/pages/LobbyPage/index.tsx
  front-end/src/pages/LobbyPage/style.scss
  front-end/src/pages/LoginPage/index.tsx
  front-end/src/pages/RegisterPage/index.tsx
  front-end/src/routes/OauthCallbackRouter/GithubCallback.tsx
  front-end/src/routes/OauthCallbackRouter/GoogleCallback.tsx
  front-end/src/routes/OauthCallbackRouter/NaverCallback.tsx
  front-end/src/routes/OauthCallbackRouter/index.tsx
Labels: 로그인🔑, 🖥. 프론트엔드, 🗄 백엔드, 공통

#124 🔨 : React Router v6🔥🔥🔥🔥🔥🔥🔥
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.tsx
  front-end/src/hooks/use-auth/index.ts
  front-end/src/pages/LobbyPage/index.tsx
  front-end/src/pages/LoginPage/index.tsx
  front-end/src/pages/RegisterPage/index.tsx
  front-end/src/routes/OauthCallbackRouter/index.tsx
  front-end/src/routes/PrivateRoute.tsx
  front-end/src/routes/RequireAuth.tsx
Labels: 🖥. 프론트엔드

#129 ✨ : Auth guard 새로고침 시 cookie 기준으로 판단
  back-end/api-server/routes/auth.ts
  back-end/socket-server/services/socket.ts
  back-end/socket-server/src/index.ts
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.tsx
  front-end/src/features/user/userAPI.ts
  front-end/src/features/user/userSlice.ts
  front-end/src/hooks/use-auth/index.ts
  front-end/src/layout/AppbarLayout/index.tsx
  front-end/src/routes/OauthCallbackRouter/GithubCallback.tsx
  front-end/src/routes/OauthCallbackRouter/GoogleCallback.tsx
  front-end/src/routes/OauthCallbackRouter/NaverCallback.tsx
  front-end/src/routes/OauthCallbackRouter/index.tsx
  front-end/src/routes/RequireAuth.tsx
  front-end/src/setupProxy.js
Labels: 로그인🔑

#131 💄 : 랭킹 페이지 전체적인 디자인
  front-end/public/assets/profile.png
  front-end/src/App.tsx
  front-end/src/pages/RankPage/index.tsx
  front-end/src/pages/RankPage/style.scss
Labels: 🎖 랭킹, 🖥. 프론트엔드

#132 ✨ : 새로운 위치 정보를 소켓에 반영
  back-end/socket-server/services/socket.ts
  back-end/socket-server/services/tetrisSocket.ts
  back-end/socket-server/src/index.ts
  front-end/public/assets/other_block.png
  front-end/public/assets/other_player_board.png
  front-end/public/assets/player_board.png
  front-end/src/components/Tetris/Board/index.tsx
  front-end/src/components/Tetris/HoldBlock/index.tsx
  front-end/src/components/Tetris/OtherBoard/index.tsx
  front-end/src/components/Tetris/PreviewBlocks/index.tsx
  front-end/src/components/Tetris/index.tsx
  front-end/src/components/Tetris/style.scss
  front-end/src/components/Tetris/types.ts
  front-end/src/constants/tetris.ts
Labels: 🧱 테트리스 기능

#133 접속자 정보 / 목록 로비 반영 && 방생성 모달 UI 작업
  back-end/api-server/middlewares/jwt.ts
  back-end/api-server/routes/auth.ts
  back-end/api-server/services/auth.ts
  back-end/socket-server/middlewares/jwt.ts
  back-end/socket-server/package-lock.json
  back-end/socket-server/package.json
  back-end/socket-server/services/socket.ts
  front-end/src/App.scss
  front-end/src/App.tsx
  front-end/src/common/assets/checkbox.png
  front-end/src/common/assets/lock.png
  front-end/src/components/Modal/index.tsx
  front-end/src/components/Modal/style.scss
  front-end/src/features/user/userSlice.ts
  front-end/src/hooks/use-auth/index.ts
  front-end/src/pages/LobbyPage/index.tsx
  front-end/src/pages/LobbyPage/style.scss
  front-end/src/pages/LoginPage/index.tsx
Labels: 🏠. 대기실, 🖥. 프론트엔드, 🗄 백엔드

#136 [랭킹] 구현 마무리
  back-end/api-server/database/query.ts
  back-end/api-server/routes/index.js
  back-end/api-server/routes/rankSearch.ts
  back-end/api-server/routes/users.js
  back-end/api-server/src/index.ts
  front-end/src/App.tsx
  front-end/src/pages/RankPage/index.tsx
  front-end/src/pages/RankPage/style.scss
Labels: 🎖 랭킹, 🖥. 프론트엔드, 🗄 백엔드

#138 프로필 페이지 작업
  back-end/api-server/database/query.ts
  back-end/api-server/package-lock.json
  back-end/api-server/routes/auth.ts
  back-end/api-server/routes/profile.ts
  back-end/api-server/routes/registerDBInsert.ts
  back-end/api-server/src/index.ts
  back-end/socket-server/package-lock.json
  front-end/package-lock.json
  front-end/public/assets/profile.png
  front-end/src/App.scss
  front-end/src/App.tsx
  front-end/src/components/Line/index.tsx
  front-end/src/components/Line/style.scss
  front-end/src/pages/LobbyPage/style.scss
  front-end/src/pages/ProfilePage/index.tsx
  front-end/src/pages/ProfilePage/style.scss
Labels: 👥 개인 프로필, 🖥. 프론트엔드

#137 대기실 기본 기능 / 게임 내 채팅 기능 구현
  back-end/socket-server/services/socket.ts
  back-end/socket-server/tsconfig.json
  front-end/public/index.html
  front-end/src/App.tsx
  front-end/src/app/store.ts
  front-end/src/common/styles/_base.scss
  front-end/src/components/Popper/index.tsx
  front-end/src/components/Popper/style.scss
  front-end/src/context/SocketContext.tsx
  front-end/src/features/socket/socketSlice.ts
  front-end/src/index.tsx
  front-end/src/layout/AppbarLayout/index.tsx
  front-end/src/pages/GamePage/index.tsx
  front-end/src/pages/GamePage/style.scss
  front-end/src/pages/LobbyPage/index.tsx
  front-end/src/pages/LobbyPage/style.scss
  front-end/src/pages/WithSocketPage/index.tsx
  front-end/src/routes/OauthCallbackRouter/index.tsx
Labels: 🏠. 대기실

#143 테트리스 멀티 게임 버그 수정
  back-end/socket-server/services/tetrisSocket.ts
  front-end/src/components/Tetris/Board/index.tsx
Labels: bug, 🧱 테트리스 기능

#142 Line 컴포넌트 제거, 오타 수정, DB 속성 변경에 따른 쿼리문 수정
  back-end/api-server/routes/profile.ts
  front-end/src/components/Line/index.tsx
  front-end/src/components/Line/style.scss
  front-end/src/pages/ProfilePage/index.tsx
  front-end/src/pages/ProfilePage/style.scss
Labels: bug, 👥 개인 프로필, 🖥. 프론트엔드

#141 🐛 : 회원가입시 토큰 발행 관련 로직 추가
  back-end/api-server/routes/registerDBInsert.ts
  front-end/src/App.scss
  front-end/src/pages/GamePage/index.tsx
  front-end/src/pages/LobbyPage/index.tsx
  front-end/src/pages/LobbyPage/style.scss
  front-end/src/pages/ProfilePage/index.tsx
  front-end/src/pages/ProfilePage/style.scss
  front-end/src/pages/RankPage/index.tsx
  front-end/src/pages/RankPage/style.scss
  front-end/src/pages/RegisterPage/index.tsx
Labels: bug, 🗄 백엔드

#150 socket-server 리팩토링
  back-end/socket-server/app.js
  back-end/socket-server/bin/www
  back-end/socket-server/constant/room.ts
  back-end/socket-server/middlewares/jwt.ts
  back-end/socket-server/public/index.html
  back-end/socket-server/public/stylesheets/style.css
  back-end/socket-server/routes/index.js
  back-end/socket-server/routes/users.js
  back-end/socket-server/services/lobbyUserSocket.ts
  back-end/socket-server/services/socket.ts
  back-end/socket-server/services/tetrisSocket.ts
  back-end/socket-server/src/index.ts
  back-end/socket-server/type/socketType.ts
  back-end/socket-server/utils/userUtil.ts
  front-end/src/context/SocketContext.tsx
  front-end/src/pages/GamePage/index.tsx
Labels: 🧱 테트리스 기능

#152 알림센터 모달 작업
  back-end/api-server/routes/auth.ts
  front-end/src/common/styles/_base.scss
  front-end/src/components/Modal/index.tsx
  front-end/src/components/Modal/style.scss
  front-end/src/pages/LobbyPage/index.tsx
  front-end/src/pages/LobbyPage/style.scss
Labels: 🏠. 대기실, 🖥. 프론트엔드

#155 Helmet 관련 코드 추가
  back-end/api-server/routes/auth.ts
  front-end/package-lock.json
  front-end/package.json
  front-end/public/index.html
  front-end/public/logo192.png
  front-end/public/logo512.png
  front-end/src/components/SEO/index.tsx
  front-end/src/index.tsx
  front-end/src/pages/GamePage/index.tsx
  front-end/src/pages/LobbyPage/index.tsx
  front-end/src/pages/LobbyPage/style.scss
Labels: 🏠. 대기실, 🖥. 프론트엔드

#154 친구 요청 관련 API 작업
  back-end/api-server/database/query.ts
  back-end/api-server/routes/friend.ts
  back-end/api-server/services/friend.ts
  back-end/api-server/src/index.ts
Labels: 🏠. 대기실, 🔔 알림, 🗄 백엔드

#157 프로필 모달, nickname 수정 기능 추가
  back-end/api-server/routes/profile.ts
  front-end/package-lock.json
  front-end/src/App.tsx
  front-end/src/components/Popper/index.tsx
  front-end/src/components/ProfileModal/index.tsx
  front-end/src/components/ProfileModal/style.scss
  front-end/src/components/UserPopper/index.tsx
  front-end/src/components/UserPopper/style.scss
  front-end/src/features/user/userSlice.ts
  front-end/src/layout/AppbarLayout/index.tsx
  front-end/src/pages/LobbyPage/index.tsx
  front-end/src/pages/ProfilePage/index.tsx
  front-end/src/pages/ProfilePage/style.scss
Labels: bug, 👥 개인 프로필, 🖥. 프론트엔드, feature

#160 [친구 요청] 내부 쿼리 수정, post->get 수정 등 작업 완료했습니다.
  back-end/api-server/routes/friend.ts
  back-end/api-server/services/friend.ts
Labels: 🏠. 대기실, 🗄 백엔드

#163 친구 관련 클라이언트 작업완료
  back-end/api-server/routes/auth.ts
  back-end/api-server/services/friend.ts
  back-end/socket-server/services/lobbyUserSocket.ts
  back-end/socket-server/services/socket.ts
  front-end/public/manifest.json
  front-end/src/app/store.ts
  front-end/src/common/styles/_base.scss
  front-end/src/components/UserPopper/index.tsx
  front-end/src/context/SocketContext.tsx
  front-end/src/features/friend/friendAPI.ts
  front-end/src/features/friend/friendSlice.ts
  front-end/src/features/user/userSlice.ts
  front-end/src/pages/LobbyPage/index.tsx
  front-end/src/pages/LobbyPage/style.scss
  front-end/src/routes/OauthCallbackRouter/index.tsx
Labels: 🏠. 대기실, 🖥. 프론트엔드

#167 게임 결과 모달 구현 및 게임 방 버그 수정
  back-end/api-server/package-lock.json
  back-end/socket-server/package-lock.json
  back-end/socket-server/package.json
  back-end/socket-server/services/lobbyUserSocket.ts
  back-end/socket-server/services/socket.ts
  back-end/socket-server/services/tetrisSocket.ts
  front-end/package-lock.json
  front-end/src/components/Modal/index.tsx
  front-end/src/components/Tetris/Board/index.tsx
  front-end/src/components/Tetris/OtherBoard/index.tsx
  front-end/src/components/Tetris/RankTable/index.tsx
  front-end/src/components/Tetris/index.tsx
  front-end/src/components/Tetris/style.scss
  front-end/src/components/Tetris/types.ts
  front-end/src/context/SocketContext.tsx
  front-end/src/pages/GamePage/index.tsx
  front-end/src/pages/GamePage/style.scss
Labels: 🧱 테트리스 기능

#174 [게임 종료 시] api-server와 연결
  back-end/api-server/routes/gameRecord.ts
  back-end/api-server/services/gameRecord.ts
  back-end/api-server/src/index.ts
  back-end/socket-server/services/tetrisSocket.ts
Labels: 🛋 방 기능

#175 테트리스 소켓 코드 리팩토링 및 버그 수정
  back-end/socket-server/package-lock.json
  back-end/socket-server/package.json
  back-end/socket-server/services/tetrisSocket.ts
  back-end/socket-server/src/index.ts
  back-end/socket-server/utils/dateUtil.ts
  back-end/socket-server/utils/tetrisUtil.ts
  front-end/src/components/Tetris/Board/index.tsx
  front-end/src/components/Tetris/OtherBoard/index.tsx
  front-end/src/pages/GamePage/index.tsx
Labels: 🧱 테트리스 기능

#179 닉네임 변경 시 생기는 오류 수정
  back-end/api-server/routes/profile.ts
  front-end/src/components/Popper/style.scss
  front-end/src/components/UserPopper/index.tsx
  front-end/src/context/SocketContext.tsx
  front-end/src/pages/ProfilePage/index.tsx
Labels: bug, 👥 개인 프로필

#181 닉네임 변경 시 생기는 오류와 소켓 복사 버그 수정
  back-end/socket-server/services/lobbyUserSocket.ts
  back-end/socket-server/services/socket.ts
  front-end/public/assets/error.png
  front-end/src/App.tsx
  front-end/src/context/SocketContext.tsx
  front-end/src/features/user/userSlice.ts
  front-end/src/layout/AppbarLayout/index.tsx
  front-end/src/pages/ErrorPage/constants.ts
  front-end/src/pages/ErrorPage/index.tsx
  front-end/src/pages/ErrorPage/style.scss
  front-end/src/pages/LobbyPage/index.tsx
  front-end/src/pages/ProfilePage/index.tsx
Labels: bug, 👥 개인 프로필

#184 게임방 키 입력 버그 수정
  front-end/src/components/Modal/index.tsx
  front-end/src/components/Tetris/Board/index.tsx
  front-end/src/constants/tetris.ts
  front-end/src/pages/GamePage/index.tsx
  front-end/src/pages/GamePage/style.scss
Labels: 🧱 테트리스 기능

#185 프로필 페이지 무한 스크롤 적용
  back-end/api-server/database/query.ts
  back-end/api-server/routes/gameRecord.ts
  back-end/api-server/routes/profile.ts
  front-end/src/components/InfiniteScroll/index.tsx
  front-end/src/components/InfiniteScroll/style.scss
  front-end/src/pages/ProfilePage/index.tsx
  front-end/src/pages/ProfilePage/style.scss
Labels: 👥 개인 프로필, feature

#187 🐛 핫 픽스 🐛
  back-end/api-server/routes/profile.ts
  front-end/src/components/InfiniteScroll/index.tsx
  front-end/src/pages/ProfilePage/index.tsx
Labels: bug

#192 코드리뷰 때 받은 프로필 관련 문제들을 해결함
  back-end/api-server/database/query.ts
  back-end/api-server/routes/api-routes/profile.ts
  front-end/src/components/InfiniteScroll/index.tsx
  front-end/src/pages/ProfilePage/index.tsx
  front-end/src/pages/ProfilePage/profileFetch.tsx
Labels: bug, 👥 개인 프로필

#197 [랭킹] 1vs1 지우기, css 작업, 검색 기능 개선
  front-end/src/pages/RankingPage/index.tsx
  front-end/src/pages/RankingPage/style.scss
Labels: 🎖 랭킹, 🖥. 프론트엔드

#198 프로필 페이지, 에러 페이지에 있는 버그를 수정
  back-end/api-server/routes/api-routes/profile.ts
  front-end/src/components/InfiniteScroll/index.tsx
  front-end/src/components/InfiniteScroll/style.scss
  front-end/src/pages/ErrorPage/constants.ts
  front-end/src/pages/ProfilePage/index.tsx
  front-end/src/pages/ProfilePage/profileFetch.tsx
  front-end/src/pages/ProfilePage/style.scss
  front-end/src/pages/RankingPage/index.tsx
  front-end/src/pages/RankingPage/rankFetch.tsx
Labels: bug, 👥 개인 프로필
